version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    networks:
      - app-network
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  producer:
    image: node:8
    # build:
      # context: ./producer
      # dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./producer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - HOSTNAMERABBIT=rabbitmq
    links:
      - rabbitmq:rabbitmq
    command: ["node", "src/index.js"]
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./consumer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - HOSTNAMERABBIT=rabbitmq
    stop_grace_period: 1m30s
    links:
      - rabbitmq:rabbitmq
networks:
  app-network:
    driver: bridge
